fixes

diff --git a/contrib/cut-release b/contrib/cut-release
--- a/contrib/cut-release
+++ b/contrib/cut-release
@@ -56,7 +56,7 @@ if ! grep '^m4_define(_CVC4_RELEASE_STRING, \[.*\])' configure.ac &>/dev/null; t
 fi
 perl -pi -e 's/^m4_define\(_CVC4_RELEASE_STRING, \[.*\]\)/m4_define(_CVC4_RELEASE_STRING, ['"$version"'])/' configure.ac
 
-trap 'echo; echo; svn revert configure.ac; echo' EXIT
+trap 'echo; echo; echo "Aborting in error."; svn revert configure.ac; echo' EXIT
 
 echo
 echo 'Made the following change to configure.ac:'
@@ -74,43 +74,42 @@ if [ -z "$(svn status -q configure.ac)" ]; then
   exit 1
 fi
 
-set -ex
-
-./autogen.sh
-./configure production-cln-staticbinary --disable-shared
-make dist "$@"
-(cd builds
-tar xf "cvc4-$version.tar.gz"
-cd "cvc4-$version"
-./configure production-cln-staticbinary --disable-shared
-#make check "$@"
-#make distcheck "$@"
+(
+	set -ex
+	./autogen.sh
+	mkdir "release-$version"
+	cd "release-$version"
+	../configure production-cln-staticbinary --disable-shared
+	make dist "$@"
+	tar xf "cvc4-$version.tar.gz"
+	cd "cvc4-$version"
+	./configure production-cln-staticbinary --disable-shared
+	#make check "$@"
+	#make distcheck "$@"
 )
-
-set +ex
 
 echo
 echo 'This release of CVC4 will identify itself as:'
 echo
-builds/cvc4-$version/builds/bin/cvc4 --version
+release-$version/src/main/cvc4 --version
 echo
 isthatright
 
 echo
 echo 'This binary release of CVC4 will identify itself as being configured like this:'
 echo
-builds/cvc4-$version/builds/bin/cvc4 --version
+release-$version/src/main/cvc4 --show-config
 echo
 isthatright
 
 echo
 echo "Signing tarball..."
-cp -p "builds/cvc4-$version.tar.gz" .
+cp -p "release-$version/cvc4-$version.tar.gz" .
 gpg -b --armor "cvc4-$version.tar.gz"
 
 echo
 echo "Signing binary..."
-cp -p "builds/cvc4-$version/builds/bin/cvc4" "cvc4-$version"
+cp -p "release-$version/src/main/cvc4" "cvc4-$version"
 gpg -b --armor "cvc4-$version"
 
 echo
@@ -122,3 +121,6 @@ echo
 echo "About to run: svn copy -m \"Cutting release $version.\" \"$root\" \"https://subversive.cims.nyu.edu/cvc4/cvc4/tags/releases/$version\""
 isthatright
 : svn copy -m "Cutting release $version." "$root" "https://subversive.cims.nyu.edu/cvc4/cvc4/tags/releases/$version"
+
+trap '' EXIT
+
