merge from trunk, sequential works

diff --git a/contrib/cut-release b/contrib/cut-release
--- a/contrib/cut-release
+++ b/contrib/cut-release
@@ -4,7 +4,11 @@
 #
 
 function isthatright {
-  echo -n "Does that look right? [y/n] "
+  if [ -z "$1" ]; then
+    echo -n "Does that look right? [y/n] "
+  else
+    echo -n "$1? [y/n] "
+  fi
   while read yn; do
     if [ "$yn" = y -o "$yn" = Y -o "$yn" = yes -o "$yn" = YES -o "$yn" = Yes ]; then
       break
@@ -43,10 +47,10 @@ if echo "$version" | grep '[^a-zA-Z0-9_.+(){}^%#-]' &>/dev/null; then
   exit 1
 fi
 
-vs=($(echo "$version" | sed 's,^\([0-9]*\)\.\([0-9]*\)\(\.\([0-9]*\)\)\?\(.*\),\1 \2 \4 \5,'))
+eval "declare -a vs=($(echo "$version" | sed 's,^\([0-9]*\)\.\([0-9]*\)\(\.\([0-9]*\)\)\?\(.*\),[0]=\1 [1]=\2 [2]=\4 [3]=\5,'))"
 major=${vs[0]}
-minor=${vs[1]}
-release=${vs[2]-0}
+minor=${vs[1]}; if [ -z "$minor" ]; then minor=0; fi
+release=${vs[2]}; if [ -z "$release" ]; then release=0; fi
 extra=${vs[3]}
 echo
 echo "Major  : $major"
@@ -111,6 +115,20 @@ if [ -n "$suspect_files" ]; then
   $dryrun || exit 1
 fi
 
+echo "Checking NEWS file for recent updates..."
+if [ -n "$(svn status -q NEWS)" ]; then
+  echo "+ It's locally modified."
+else
+  echo -n "+ "
+  svn info NEWS | grep '^Last Changed Date: '
+  echo
+  echo "You should probably make sure to put some notes in the NEWS file"
+  echo "for this release, indicating the most important changes from the"
+  echo "last release."
+  echo
+  isthatright "Continue without updating NEWS"
+fi
+
 echo "Adjusting version info lines in configure.ac..."
 if ! grep '^m4_define(_CVC4_MAJOR,  *[0-9][0-9]* *)' configure.ac &>/dev/null ||
    ! grep '^m4_define(_CVC4_MINOR,  *[0-9][0-9]* *)' configure.ac &>/dev/null ||
@@ -149,14 +167,14 @@ echo "Building and checking distribution \`cvc4-$version'..."
 if ! $SHELL -c '\
 	version="'$version'"; \
 	set -ex; \
-	./autogen.sh; \
+	./autogen.sh || echo "autoconf failed; does library_versions have something to match $version?"; \
 	mkdir "release-$version"; \
 	cd "release-$version"; \
-	../configure production-cln-staticbinary --disable-shared --enable-unit-testing --with-cudd --with-readline; \
+	../configure production-cln-staticbinary --disable-shared --enable-unit-testing --without-cudd --with-readline --with-portfolio; \
 	make dist "$@"; \
 	tar xf "cvc4-$version.tar.gz"; \
 	cd "cvc4-$version"; \
-	./configure production-cln-staticbinary --disable-shared --enable-unit-testing --with-cudd --with-readline; \
+	./configure production-cln-staticbinary --disable-shared --enable-unit-testing --without-cudd --with-readline --with-portfolio; \
 	make check "$@"; \
 	make distcheck "$@"; \
 '; then
@@ -192,9 +210,14 @@ cp -p "release-$version/cvc4-$version.tar.gz" .
 gpg -b --armor "cvc4-$version.tar.gz"
 
 echo
-echo "Signing binary..."
+echo "Signing cvc4 binary..."
 cp -p "release-$version/src/main/cvc4" "cvc4-$version"
 gpg -b --armor "cvc4-$version"
+
+echo
+echo "Signing pcvc4 binary..."
+cp -p "release-$version/src/main/pcvc4" "pcvc4-$version"
+gpg -b --armor "pcvc4-$version"
 
 echo
 echo "About to run: svn commit -m \"Cutting release $version.\""
@@ -205,6 +228,27 @@ echo
 echo "About to run: svn copy -m \"Cutting release $version.\" \"$root\" \"https://subversive.cims.nyu.edu/cvc4/cvc4/tags/releases/$version\""
 isthatright
 $dryrun || svn copy -m "Cutting release $version." "$root" "https://subversive.cims.nyu.edu/cvc4/cvc4/tags/releases/$version"
+
+echo
+if [ "$(svn info | grep '^URL: https://subversive.cims.nyu.edu/cvc4/cvc4/trunk$')" ]; then
+  if [ "$release" = 0 ]; then
+    echo "About to run: svn copy -m \"Branching release $version for bugfixes.\" \"https://subversive.cims.nyu.edu/cvc4/cvc4/tags/releases/$version\" \"https://subversive.cims.nyu.edu/cvc4/cvc4/branches/releases/$version.x\""
+    isthatright
+    $dryrun || svn copy -m "Branching release $version for bugfixes." "https://subversive.cims.nyu.edu/cvc4/cvc4/tags/releases/$version" "https://subversive.cims.nyu.edu/cvc4/cvc4/branches/releases/$version.x"
+  else
+    echo "Not branching, because this is a minor release (i.e., not a \"dot-oh\""
+    echo "release), so I'm guessing you have a devel repository outside of trunk"
+    echo "somewhere?  You can still make a branch manually, of course."
+  fi
+else
+  echo "Not branching, because it appears there already is a branch"
+  echo "to work with for version $version ..?  (You're not on trunk.)"
+  echo "You can still make a branch manually, of course."
+fi
+
+echo
+echo "Done.  Next steps are to upload and advertise these packages and to add"
+echo "a $version release to Bugzilla."
 
 trap '' EXIT
 
diff --git a/src/theory/mktheorytraits b/src/theory/mktheorytraits
--- a/src/theory/mktheorytraits
+++ b/src/theory/mktheorytraits
@@ -2,7 +2,7 @@
 #
 # mktheorytraits
 # Morgan Deters <mdeters@cs.nyu.edu> for CVC4
-# Copyright (c) 2010-2011  The CVC4 Project
+# Copyright (c) 2010-2012  The CVC4 Project
 #
 # The purpose of this script is to create theory_traits.h from a template
 # and a list of theory kinds.
@@ -14,11 +14,13 @@
 # Output is to standard out.
 #
 
-copyright=2010-2011
+copyright=2010-2012
+
+filename=`basename "$1" | sed 's,_template,,'`
 
 cat <<EOF
 /*********************                                                        */
-/** theory_traits.h
+/** $filename
  **
  ** Copyright $copyright  The AcSys Group, New York University, and as below.
  **
@@ -40,12 +42,16 @@ theory_includes=
 theory_for_each_macro="#define CVC4_FOR_EACH_THEORY \\
 "
 
+type_enumerator_includes=
+mk_type_enumerator_cases=
+
 theory_has_check="false"
 theory_has_propagate="false"
-theory_has_staticLearning="false"
+theory_has_ppStaticLearn="false"
 theory_has_notifyRestart="false"
 theory_has_presolve="false"
 theory_has_postsolve="false"
+theory_has_getNextDecisionRequest="false"
 
 theory_stable_infinite="false"
 theory_finite="false"
@@ -55,8 +61,14 @@ theory_parametric="false"
 rewriter_class=
 rewriter_header=
 
+instantiator_class=void
+instantiator_header=
+
 theory_id=
 theory_class=
+
+type_constants=
+type_kinds=
 
 seen_theory=false
 seen_theory_builtin=false
@@ -123,6 +135,7 @@ template<>
 struct TheoryTraits<${theory_id}> {
     typedef ${theory_class} theory_class;
     typedef ${rewriter_class} rewriter_class;
+    typedef ${instantiator_class} instantiator_class;
 
     static const bool isStableInfinite = ${theory_stable_infinite};
     static const bool isFinite = ${theory_finite};
@@ -131,36 +144,37 @@ struct TheoryTraits<${theory_id}> {
 
     static const bool hasCheck = ${theory_has_check};
     static const bool hasPropagate = ${theory_has_propagate};
-    static const bool hasStaticLearning = ${theory_has_staticLearning};
+    static const bool hasPpStaticLearn = ${theory_has_ppStaticLearn};
     static const bool hasNotifyRestart = ${theory_has_notifyRestart};
     static const bool hasPresolve = ${theory_has_presolve};
     static const bool hasPostsolve = ${theory_has_postsolve};
+    static const bool hasGetNextDecisionRequest = ${theory_has_getNextDecisionRequest};
 };/* struct TheoryTraits<${theory_id}> */
 "
 
   # warnings about theory content and properties
-  # TODO: fix, not corresponding to staticLearning anymore
-  # dir="$(dirname "$kf")/../../"
-  # if [ -e "$dir/$theory_header" ]; then
-  #   for function in check propagate staticLearning notifyRestart presolve postsolve; do
-  #      if eval "\$theory_has_$function"; then
-  #        grep '\<'"$function"' *\((\|;\)' "$dir/$theory_header" | grep -vq '^ */\(/\|\*\)' ||
-  #          echo "$kf: warning: $theory_class has property \"$function\" in its kinds file but doesn't appear to declare the function" >&2
-  #      else
-  #        grep '\<'"$function"' *\((\|;\)' "$dir/$theory_header" | grep -vq '^ */\(/\|\*\)' &&
-  #          echo "$kf: warning: $theory_class does not have property \"$function\" in its kinds file but appears to declare the function" >&2
-  #      fi
-  #    done
-  # else
-  #   echo "$me: warning: theory header \"$theory_header\" does not exist or is unreadable" >&2
-  # fi
+  dir="$(dirname "$kf")/../../"
+  if [ -e "$dir/$theory_header" ]; then
+    for function in check propagate ppStaticLearn notifyRestart presolve postsolve getNextDecisionRequest; do
+       if eval "\$theory_has_$function"; then
+         grep '\<'"$function"' *\((\|;\)' "$dir/$theory_header" | grep -vq '^ */\(/\|\*\)' ||
+           echo "$kf: warning: $theory_class has property \"$function\" in its kinds file but doesn't appear to declare the function" >&2
+       else
+         grep '\<'"$function"' *\((\|;\)' "$dir/$theory_header" | grep -vq '^ */\(/\|\*\)' &&
+           echo "$kf: warning: $theory_class does not have property \"$function\" in its kinds file but appears to declare the function" >&2
+       fi
+     done
+  else
+    echo "$me: warning: theory header \"$theory_header\" does not exist or is unreadable" >&2
+  fi
 
   theory_has_check="false"
   theory_has_propagate="false"
-  theory_has_staticLearning="false"
+  theory_has_ppStaticLearn="false"
   theory_has_notifyRestart="false"
   theory_has_presolve="false"
   theory_has_postsolve="false"
+  theory_has_getNextDecisionRequest="false"
 
   theory_stable_infinite="false"
   theory_finite="false"
@@ -173,7 +187,39 @@ struct TheoryTraits<${theory_id}> {
   theory_id=
   theory_class=
 
+  type_constants=
+  type_kinds=
+
   lineno=${BASH_LINENO[0]}
+}
+
+function enumerator {
+  # enumerator KIND enumerator-class header
+  lineno=${BASH_LINENO[0]}
+  check_theory_seen
+  type_enumerator_includes="${type_enumerator_includes}
+#line $lineno \"$kf\"
+#include \"$3\""
+  if expr "$type_constants" : '.* '"$1"' ' &>/dev/null; then
+    mk_type_enumerator_type_constant_cases="${mk_type_enumerator_type_constant_cases}
+#line $lineno \"$kf\"
+    case $1:
+#line $lineno \"$kf\"
+      return new $2(type);
+"
+  elif expr "$type_kinds" : '.* '"$1"' ' &>/dev/null; then
+    mk_type_enumerator_cases="${mk_type_enumerator_cases}
+#line $lineno \"$kf\"
+  case kind::$1:
+#line $lineno \"$kf\"
+    return new $2(type);
+"
+  else
+    echo "$kf:$lineno: error: don't know anything about $1; enumerator must appear after definition" >&2
+    echo "type_constants: $type_constants" >&2
+    echo "type_kinds    : $type_kinds" >&2
+    exit 1
+  fi
 }
 
 function typechecker {
@@ -186,6 +232,24 @@ function typerule {
   # typerule OPERATOR typechecking-class
   lineno=${BASH_LINENO[0]}
   check_theory_seen
+}
+
+function construle {
+  # construle OPERATOR isconst-checking-class
+  lineno=${BASH_LINENO[0]}
+  check_theory_seen
+}
+
+function instantiator {
+  # instantiator class header
+  lineno=${BASH_LINENO[0]}
+  check_theory_seen
+
+  instantiator_class="$1"
+  instantiator_header="$2"
+
+  theory_includes="${theory_includes}#include \"$2\"
+"
 }
 
 function properties {
@@ -202,9 +266,10 @@ function properties {
        polite) theory_polite="true";;
        check) theory_has_check="true";;
        propagate) theory_has_propagate="true";;
-       staticLearning) theory_has_staticLearning="true";;
+       ppStaticLearn) theory_has_ppStaticLearn="true";;
        presolve) theory_has_presolve="true";;
        postsolve) theory_has_postsolve="true";;
+       getNextDecisionRequest) theory_has_getNextDecisionRequest="true";;
        notifyRestart) theory_has_notifyRestart="true";;
        *) echo "$kf:$lineno: error: unknown theory property \"$property\"" >&2; exit 1;;
     esac
@@ -269,6 +334,7 @@ function register_sort {
   comment=$3
   type_constant_to_theory_id="${type_constant_to_theory_id}   case $id: return $theory_id; break;
 "
+  type_constants="${type_constants} $1 "
 }
 
 function register_kind {
@@ -277,6 +343,7 @@ function register_kind {
   comment=$3
   kind_to_theory_id="${kind_to_theory_id}   case kind::$r: return $theory_id; break;
 "
+  type_kinds="${type_kinds} $1 "
 }
 
 function check_theory_seen {
@@ -326,6 +393,9 @@ for var in \
     theory_for_each_macro \
     theory_includes \
     template \
+    type_enumerator_includes \
+    mk_type_enumerator_type_constant_cases \
+    mk_type_enumerator_cases \
     ; do
   eval text="\${text//\\\$\\{$var\\}/\${$var}}"
 done
