Merged trunk into the branch.

diff --git a/wipe-tabelau-on-restart/Makefile b/wipe-tabelau-on-restart/Makefile
--- a/wipe-tabelau-on-restart/Makefile
+++ b/wipe-tabelau-on-restart/Makefile
@@ -42,15 +42,65 @@ examples: all
 	(cd examples && $(MAKE) $(AM_MAKEFLAGS))
 
 YEAR := $(shell date +%Y)
-submission:
-	if [ ! -e configure ]; then ./autogen.sh; fi
-	./configure competition --disable-shared --enable-static-binary --with-cln
+submission submission-main:
+	@if [ -n "`ls src/parser/*/generated 2>/dev/null`" ]; then \
+	  echo 'ERROR:' >&2; \
+	  echo 'ERROR: Please make maintainer-clean first.' >&2; \
+	  echo 'ERROR:' >&2; \
+	  exit 1; \
+        fi
+	./autogen.sh
+	./configure competition --disable-shared --enable-static-binary --with-cln --without-cudd
 	$(MAKE)
 	strip builds/bin/cvc4
-	$(MAKE) regress1
+	$(MAKE) check
+	$(MAKE) -C test/regress/regress1 check
+	# main track
 	mkdir -p cvc4-smtcomp-$(YEAR)
 	cp -p builds/bin/cvc4 cvc4-smtcomp-$(YEAR)/cvc4
-	( echo '#!/bin/sh'; \
-	  echo 'exec ./cvc4 -L smt2 --no-interactive' ) > cvc4-smtcomp-$(YEAR)/run
+	cp contrib/run-script-smtcomp2012 cvc4-smtcomp-$(YEAR)/run
 	chmod 755 cvc4-smtcomp-$(YEAR)/run
 	tar cf cvc4-smtcomp-$(YEAR).tar cvc4-smtcomp-$(YEAR)
+submission-application:
+	# application track is a separate build because it has different preprocessor #defines
+	@if [ -n "`ls src/parser/*/generated 2>/dev/null`" ]; then \
+	  echo 'ERROR:' >&2; \
+	  echo 'ERROR: Please make maintainer-clean first.' >&2; \
+	  echo 'ERROR:' >&2; \
+	  exit 1; \
+        fi
+	./autogen.sh
+	./configure competition --disable-shared --enable-static-binary --with-cln --without-cudd CXXFLAGS=-DCVC4_SMTCOMP_APPLICATION_TRACK CFLAGS=-DCVC4_SMTCOMP_APPLICATION_TRACK
+	$(MAKE)
+	strip builds/bin/cvc4
+	$(MAKE) check
+	$(MAKE) -C test/regress/regress1 check
+	# package the application track tarball
+	mkdir -p cvc4-application-smtcomp-$(YEAR)
+	cp -p builds/bin/cvc4 cvc4-application-smtcomp-$(YEAR)/cvc4
+	( echo '#!/bin/sh'; \
+	  echo 'exec ./cvc4 -L smt2 --no-checking --no-interactive --incremental' ) > cvc4-application-smtcomp-$(YEAR)/run
+	chmod 755 cvc4-application-smtcomp-$(YEAR)/run
+	tar cf cvc4-application-smtcomp-$(YEAR).tar cvc4-application-smtcomp-$(YEAR)
+submission-parallel:
+	# parallel track can't be built with -cln, so it's a separate build
+	@if [ -n "`ls src/parser/*/generated 2>/dev/null`" ]; then \
+	  echo 'ERROR:' >&2; \
+	  echo 'ERROR: Please make maintainer-clean first.' >&2; \
+	  echo 'ERROR:' >&2; \
+	  exit 1; \
+        fi
+	./autogen.sh
+	./configure competition --disable-shared --enable-static-binary --with-gmp --without-cudd --with-portfolio
+	$(MAKE)
+	strip builds/bin/pcvc4
+	# some test cases fail (and are known to fail)
+	-$(MAKE) check BINARY=pcvc4
+	$(MAKE) -C test/regress/regress1 check BINARY=pcvc4
+	# package the parallel track tarball
+	mkdir -p cvc4-parallel-smtcomp-$(YEAR)
+	cp -p builds/bin/pcvc4 cvc4-parallel-smtcomp-$(YEAR)/pcvc4
+	( echo '#!/bin/sh'; \
+	  echo 'exec ./pcvc4 --threads 2 -L smt2 --no-checking --no-interactive' ) > cvc4-parallel-smtcomp-$(YEAR)/run
+	chmod 755 cvc4-parallel-smtcomp-$(YEAR)/run
+	tar cf cvc4-parallel-smtcomp-$(YEAR).tar cvc4-parallel-smtcomp-$(YEAR)
